FROM node:18-bullseye

# Set the working directory
WORKDIR /cdk-validium-contracts

# Copy package.json and package-lock.json to the container
COPY package*.json ./

# Install cdk-validium-contracts dependencies
RUN npm install

# Copy the needed files
COPY node_modules/ node_modules/
COPY compiled-contracts/CDKDataCommittee.json compiled-contracts/
COPY docker/scripts/setup-committee.js docker/scripts/

CMD ["npm", "run", "setup:committee"]